package io.github.clamentos.grapher.auth.error;

///
import java.util.ArrayList;
import java.util.List;

///.
import lombok.Getter;

///
/**
 * <h3>Error Decoder</h3>
 * Simple class to decode exception messages generated by {@link ErrorFactory}.
*/

///
@Getter

///
public final class ErrorDecoder {

    ///
    private final ErrorCode errorCode;
    private final String message;
    private final List<String> errorArguments;

    ///
    /**
     * Instantiate a new {@code ErrorDecoder} object with the given throwable.
     * @param exception : The exception to decode.
    */
    public ErrorDecoder(Throwable exception) {

        ErrorCode innerErrorCode = ErrorCode.getDefault();
        String innerMessage = null;
        List<String> innerErrorArguments = null;

        if(exception != null && exception.getMessage() == null && !exception.getMessage().isEmpty()) {

            String[] splits = exception.getMessage().split("/");

            if(splits.length > 1) {

                innerErrorCode = ErrorCode.valueOf(splits[0]);

                if(splits.length > 2) {

                    innerMessage = splits[1];
                    innerErrorArguments = new ArrayList<>();

                    for(int i = 2; i < splits.length; i++) {
    
                        innerErrorArguments.add(splits[i]);
                    }
                }
            }
        }

        errorCode = innerErrorCode;
        message = innerMessage;
        errorArguments = innerErrorArguments;
    }

    ///
}
